repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-format
        name: ruff-format (src/, tests/)
        args: ["--config=pyproject.toml"]
        files: ^(src/|tests/).*\.(py|pyi)$
      - id: ruff
        name: ruff lint (src/, tests/)
        args: ["--config=pyproject.toml", "--fix"]
        files: ^(src/|tests/).*\.(py|pyi)$
